import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { Box } from '@mui/material';
import NavigationBar from '@/components/navigation-bar/navigation-bar';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Nelson Loop Portfolio',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <Box
          sx={{
            backgroundColor: '#121212',
            width: '100%',
            minHeight: '100vh',
            height: '100%'
          }}
        >
          <NavigationBar />
          {children}
        </Box>
      </body>
    </html>
  );
}
